# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - EDUWebAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        # Change directory to the solution or main project folder
        run: |
          cd Api/Api.AppHost
          dotnet build --configuration Release

      - name: dotnet publish
        # Change directory to the solution or main project folder before publishing
        run: |
          cd Api/Api.AppHost
          dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/Api" # The output path remains the same relative to the original root
          # Note: The output directory "${{env.DOTNET_ROOT}}/Api" will be C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\Api
          # Make sure this output path makes sense for your artifact. If you want the published output
          # to be relative to your repository root, you might consider an absolute path like 'C:\a\your-repo\published_app'
          # or a relative path from the current directory, but ensure 'upload-artifact' picks it up correctly.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          # The path here should point to where dotnet publish placed the files.
          # If dotnet publish -o "${{env.DOTNET_ROOT}}/Api" was run from Api/Api.AppHost,
          # then the published output is at C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\Api.
          path: ${{env.DOTNET_ROOT}}/Api
